#install.packages("music")
library(music)
playNote("C")
Sys.sleep(0.5)
playNote("C")
Sys.sleep(0.5)
playNote("G");Sys.sleep(0.5)
playNote("G");Sys.sleep(0.5)
playNote("A");Sys.sleep(0.5)
playNote("A");Sys.sleep(0.5)
playNote("G", duration = 2);Sys.sleep(0.5)
